---
application_name: Rails_CodeBase
business_name: Rails_CodeBase, LLC
business_address: 
domain: localhost
support_email: support@localhost.co
default_from_email: Rails_CodeBase <no-reply@localhost.co>
background_job_processor: sidekiq
email_provider: postmark
personal_accounts: false
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
- stripe
multitenancy:
gems:
- acts_as_tenant
- rack-attack
- whenever
